[package]
authors = ["Naoki Fujita <fujitanaoki0718@gmail.com>"]
edition = "2021"
name = "rust_studies"
version = "0.1.0"

[dependencies]
arraydeque = "*"
bounded-vec-deque = "*"
circular-queue = "*"
criterion = "*"
itertools = "*"
rb = "*"

[[bench]]
harness = false
name = "ring_buffers"
