version: "3.9"

services:
  rails_basics:
    container_name: rails_basics
    image: ruby:3.1.2
    networks:
      - mysql_default
    ports:
      - "53000:3000"
    volumes:
      - type: bind
        source: ./
        target: /myapp
    tty: true
    user: "${UID}:${GID}"
networks:
  mysql_default:
    external: true