---
includes: [../protos]
files:
  - ../protos/protobuf/v1/exhaustive.proto
  - ../protos/protobuf/v1/hello.proto
  - ../protos/protobuf/v1/migrate.proto
  - ../protos/protobuf/v2/migrate.proto
messages:
  - paths: [protobuf.v1.Hello]
    attrs:
      - derive(serde::Serialize, serde::Deserialize)
      - serde(default)
  - paths: [protobuf.v1.World]
    attrs:
      - derive(serde::Serialize, serde::Deserialize)
      - serde(default)

enums:
  - paths: [protobuf.v1.HelloStatus]
    attrs:
      - derive(serde::Serialize, serde::Deserialize)
      - serde(rename_all = "lowercase")

fields:
  - paths:
      - msg
    attrs:
      - serde(skip_serializing_if = "String::is_empty", default)
  - paths:
      - field_may_be_null
    attrs:
      - serde(deserialize_with = "prost_helper::deserialize_null_default")
  - path:
      - field_skip_zero
    attrs:
      - serde(skip_serializing_if = "prost_helper::is_zero")
  - path:
      - field_skip
    attrs:
      - serde(skip_serializing)
  - paths:
      - Hello.data1
      - Hello.data2
    attrs:
      - serde(serialize_with = "prost_helper::serialize_buf",deserialize_with = "prost_helper::deserialize_buf_bytes")
  - paths:
      - Hello.map
    attrs:
      - serde(serialize_with = "prost_helper::serialize_repeat_buf",deserialize_with = "prost_helper::deserialize_repeat_buf_bytes")
  - paths:
      - Hello.list_data
    attrs:
      - serde(serialize_with = "prost_helper::serialize_repeat_buf", deserialize_with = "prost_helper::deserialize_repeat_buf_bytes")
bytes:
  - .
