[package]
authors = ["Naoki Fujita <fujitanaoki0718@gmail.com>"]
edition = "2021"
name = "rust_studies"
version = "0.1.0"

[dependencies]
aes-gcm = "*"
arraydeque = "*"
async-shutdown = "*"
bondi = "*"
bounded-vec-deque = "*"
bus = "*"
chrono = "*"
circular-queue = "*"
criterion = {version = "*", features = ["html_reports"]}
futures = "^0.3.19"
itertools = "*"
keepass = "*"
maplit = "*"
multiqueue2 = "*"
nix = "*"
rb = "*"
rpassword = "*"
serde = {version = "*", features = ["derive"]}
serde_json = "*"
tokio = {version = "*", features = ["full"]}
tokio-stream = "*"

[[bench]]
harness = false
name = "ring_buffers"

[[bench]]
harness = false
name = "message_buses"

[[bench]]
harness = false
name = "fan_in"

[[bin]]
name = "rpassword"
path = "src/rpassword.rs"

[[bin]]
name = "async_shutdown"
path = "src/async_shutdown.rs"
